### ISSUE TITLE
pharokka.tbl files are empty for conda install v1.0.0

### ISSUE THREAD

**Issue by npbhavya** [gbouras13/pharokka#204]
* phrokka version: v1.0.0
* Python version: v3.9, conda install 
* Operating System: 

### Description
I ran pharokka on phage genomes, the input fasta file has a complete phage genome. The command run, 
pharokka.py -i {input} -o {params.o} -d {params.db} -t {threads} -f

### What I Did
The output has not errors, and the gbk and gff files are populated, but the pharokka.tbl is empty.

**Comment by gbouras13** [comment]
Hi NP,

I cannot seem to re-produce this error - perhaps try running your genomes again with pharokka v1.1.0. 

I will leave this issue open for now.

George

**Comment by gbouras13** [comment]
Closing after some time - if problem appears again (in v1.2.0 coming in a bit) please reopen.
