### ISSUE TITLE
Add pharokka as a toot to galaxy

### ISSUE THREAD

**Issue by paulzierep** [gbouras13/pharokka#237]
I would like to add pharokka as a toot to galaxy. In order to write the wrapper, I would need a small DB that can be added for the test case. Could you provide a minimal example of the DB, that can be used for this purpose. The DB would need to allow for the execution of the tool, the output does not need to be meaningful. The real DB can be added to galaxy instance later.

**Comment by gbouras13** [comment]
Hi Paul,

I would absolutely love this and would really appreciate you doing it! I’ll sort this out tomorrow, how small would the DB need to be? Perhaps it may better to continue this discussion over email if you prefer, george.bouras@adelaide.edu.au . 

George

**Comment by paulzierep** [comment]
There we go https://usegalaxy.eu/?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fiuc%2Fpharokka%2Fpharokka%2F1.2.1%2Bgalaxy1&version=1.2.1%20galaxy1
