### ISSUE TITLE
Issue with PHAROKKA 1.1.0 or 1.2.0 intsallation

### ISSUE THREAD

**Issue by magbphp** [gbouras13/pharokka#238]
* phrokka version: 1.1.0
* Python version: 3.9
* Operating System: Unbuntu 20.04.2

### Description

I am trying to install PHAROKKA from Github using conda or mamba. I tried on 3 different machines (1 MAC OS X and 2 PC running Ubuntu). And I always failed. I tried PHAROKKA 1.1.0 as well as 1.2.0. Databases do install properly but when I type the Help command pharroka.py -h I always get the following messages. Can you help me ?

Thanks
Nico

### What I Did

```
Traceback (most recent call last):
  File "/home/julia/miniconda3/envs/pharokkaENV/bin/pharokka.py", line 5, in <module>
    import processes
  File "/home/julia/miniconda3/envs/pharokkaENV/bin/processes.py", line 8, in <module>
    from BCBio import GFF
  File "/home/julia/miniconda3/envs/pharokkaENV/lib/python3.9/site-packages/BCBio/GFF/__init__.py", line 3, in <module>
    from BCBio.GFF.GFFParser import GFFParser, DiscoGFFParser, GFFExaminer, parse, parse_simple
  File "/home/julia/miniconda3/envs/pharokkaENV/lib/python3.9/site-packages/BCBio/GFF/GFFParser.py", line 34, in <module>
    from Bio.Seq import UnknownSeq
ImportError: cannot import name 'UnknownSeq' from 'Bio.Seq' (/home/julia/miniconda3/envs/pharokkaENV/lib/python3.9/site-packages/Bio/Seq.py)
```

**Comment by gbouras13** [comment]
Hi @magbphp ,

Thanks for pointing this out to me.

I think the error is with the new version 1.81 of biopython, specifically this [issue](https://github.com/chapmanb/bcbb/issues/136).

Please reinstall pharokka as follows:

conda install pharokka biopython=1.80.

Which should fix the error.  Let me know if it does not work.

I will change the environment and bioconda recipe as well.

George

**Comment by gbouras13** [comment]
This should now be fixed with v1.2.1 which is available on bioconda.

**Comment by bernt-matthias** [comment]
FYI: I guess it might have been a bit better to pin at bcbio-gff, like so https://github.com/bioconda/bioconda-recipes/pull/39703  .. and pin the latest bcbio-gff version in the pharokka recipe .. but the additional pin on biopython at the pharokka recipe also should not  hurt.

**Comment by gbouras13** [comment]
Thanks @bernt-matthias, I should probably just get rid of the dependency all together to be honest, maybe for the next version update when I get some time.

And thanks for your work in getting Pharokka onto Galaxy (presumably where this arose looking at the PR there) - I really appreciate it!

George
