### ISSUE TITLE
pharokka's  default mash version error  

### ISSUE THREAD

**Issue by Preonath** [gbouras13/pharokka#240]
* phrokka version:1.2.1
* Python version:3.10.8
* Operating System:Ubuntu 18.04.6 LTS

I had tried to run pharokka after installing according to README.md 

Command:
 ./bin/pharokka.py -i /path/contigs.fasta -o /path/pharokka_result -d /path/pharokka_v1.2.0_databases -t 92 -f

Error:

Starting pharokka v1.2.1
Checking database installation.
All databases have been successfully checked.
Checking dependencies.
Phanotate version found is v1.5.0.
Phanotate version is ok.
MMseqs2 version found is v13.45111.
MMseqs2 version is ok.
tRNAscan-SE version found is v2.0.11.
tRNAscan-SE version is ok.
MinCED version found is v0.4.2.
MinCED version is ok.
ARAGORN version found is v1.2.41.
ARAGORN version is ok.
Traceback (most recent call last):
  File "/media/chrf/Home03/Trial_Preonath/pharokka/bin/pharokka.py", line 87, in <module>
    input_commands.check_dependencies(logger)
  File "/media/chrf/Home03/Trial_Preonath/pharokka/bin/input_commands.py", line 313, in check_dependencies
    mash_version = version_line[0].split(' ')[2]
IndexError: list index out of range

Solution:
Then I had checked the mash version and Installed the specifie mash version
    Command:
    conda install -c bioconda mash=2.2

**Comment by gbouras13** [comment]
Hi @Preonath,

Thanks for raising this issue. It looks similar to #235 - glad that it was easy for you to solve by simply using mash 2.2.

I will close this issue as a result. 

Also - 92 threads! I've never run pharokka on so many. If you are running a big metagenome sample, I'd be interested in some details on runtime etc if you are willing to share (email george.bouras@adelaide.edu.au is best).

George

**Comment by Preonath** [comment]
Thanks @gbouras13,
Ofcourse, I'm happy to share you any information. 
For me, one sample (40.5 kB file size of contig) take time:-
real    1m12.825s
user    90m54.374s
sys     0m49.511s
where t = 96
