### ISSUE TITLE
empty VFDB and CARD counts in functions.tsv despite hits to both in top_hits_[].tsv

### ISSUE THREAD

**Issue by sxh1136** [gbouras13/pharokka#243]
* phrokka version: v1.1.0
* Python version: 3.8.16
* Operating System: Ubuntu

### Description

pharokka_cds_functions.tsv lists every single contig as having 0 VF or CARD AMR genes despite there being many hits in both the top_hits_vfdb.tsv and top_hits_card.tsv. For example when I grep "NODE_190_length_23790_cov_6.801601" on  pharokka_cds_final_merged_output.tsv I find a VF hit to 

VFG000477(gb|NP_461845) (rpoS) RNA polymerase sigma factor RpoS [RpoS (VF0112) - Regulation (VFC0301)] [Salmonella enterica subsp. enterica serovar Typhimurium str. LT2]

However when i grep NODE_190_length_23790_cov_6.801601 to pharokka_cds_functions.tsv I get:

CDS     31      NODE_190_length_23790_cov_6.801601
connector       0       NODE_190_length_23790_cov_6.801601
DNA, RNA and nucleotide metabolism      0       NODE_190_length_23790_cov_6.801601
head and packaging      0       NODE_190_length_23790_cov_6.801601
integration and excision        0       NODE_190_length_23790_cov_6.801601
lysis   0       NODE_190_length_23790_cov_6.801601
moron, auxiliary metabolic gene and host takeover       1       NODE_190_length_23790_cov_6.801601
other   1       NODE_190_length_23790_cov_6.801601
tail    0       NODE_190_length_23790_cov_6.801601
transcription regulation        1       NODE_190_length_23790_cov_6.801601
unknown function        28      NODE_190_length_23790_cov_6.801601
tRNAs   0       NODE_190_length_23790_cov_6.801601
CRISPRs 0       NODE_190_length_23790_cov_6.801601
tmRNAs  0       NODE_190_length_23790_cov_6.801601
VFDB_Virulence_Factors  0       NODE_190_length_23790_cov_6.801601
CARD_AMR_Genes  0       NODE_190_length_23790_cov_6.801601

```
pharokka.py -i impact1_vOTU.fna -o impact1_vOTU_pharokka -d /home/ubuntu/sdb/stan/db/pharokka -t 16 -m
```

**Comment by gbouras13** [comment]
Hi @sxh1136,

I believe this was a bug with v1.1.0.

Can you try updating to v1.2.1 (or v1.2.0) and trying running your command again - you will also need to redownload the updated database 

Please let me know if the issue persists.

George

**Comment by sxh1136** [comment]
Hi there, I tried it v1.2.1 and the new database but still have the same issue. I've attached the log file.
[pharokka_04042023_101446.log](https://github.com/gbouras13/pharokka/files/11151292/pharokka_04042023_101446.log)

**Comment by gbouras13** [comment]
Hi @sxh1136 ,

I can confirm that this is a bug in pharokka v1.2.1 as well (presumably caused by the meta mode) - I managed to recreate the error with the same contig names (presumably coming from Spades?).

I'll put in a fix and let you know when it is live.

George
