### ISSUE TITLE
curl and tar are not in the conda recipe

### ISSUE THREAD

**Issue by paulzierep** [gbouras13/pharokka#250]
* phrokka version:1.2.1
* Python version:3.8
* Operating System:docker, biocontainer

### Description
I found the probably reason for https://github.com/gbouras13/pharokka/issues/241 and https://github.com/gbouras13/pharokka/issues/236

curl and tar are not in the conda recipe, those commands are used by   
install_databases.py, which fails if they are not installed, which is e.g. the case if you use pharokka in 
a container (biocontainer) and galaxy

I made a PR to bioconda (https://github.com/bioconda/bioconda-recipes/pull/40481)

**Comment by gbouras13** [comment]
Thanks Paul, I imagine they would be at the root of the issue.

The only issue with the conda recipe build I can foresee for the DB integration is that it is for the recent v 1.3.0 not v 1.2.1.

George

**Comment by gbouras13** [comment]
This is in the latest conda release now so closing
