### ISSUE TITLE
No  *cds_functions.tsv in the output file

### ISSUE THREAD

**Issue by diedie9** [gbouras13/pharokka#251]
* phrokka version: v1.2.1
* Python version:  2.10.8
* Operating System: Linux

### Description
I want to use 
'./pharokka.py -i /work/hudi/lina/vir/checkv_outputs/LINA00089K_/vir_high_quality.fna -o /work/hudi/lina/vir/pharokka/separa_4/ -t 8 -f'
to get the *cds_functions.tsv.

Actually, it already generate a lot of output files. But it didn't contain this file.
'CARD              cleaned_phanotate.tsv  phanotate_aas_tmp.fasta  pharokka_04102023_151937.log  pharokka_minced_spacers.txt  trnascan_out.gff  vfdb_tmp_dir
CARD_results.tsv  mmseqs                 phanotate_out_tmp.fasta  pharokka_aragorn.txt          tmp_dir                      vfdb
CARD_tmp_dir      mmseqs_results.tsv     phanotate_out.txt        pharokka_minced.gff           top_hits_mmseqs.tsv          vfdb_results.tsv'

It also didn't have error message in the log file

I don't know why.

**Comment by gbouras13** [comment]
Hi @diedie9,

First of all I would recommend that you update to v1.3.0 (fixes a bug with the cds_functions.tsv #243).

Secondly, pharokka clearly failed to run - would you be able to upload the log file so I can have a look? I might be able to figure out the error.

George

**Comment by diedie9** [comment]
Hi George,

Thanks for your suggestion.
I got the results that I want after update the version.

Die

**Comment by gbouras13** [comment]
Beautiful closing this now.
