### ISSUE TITLE
Error in tRNAscan-SE step

### ISSUE THREAD

**Issue by phagecat** [gbouras13/pharokka#252]
* phrokka version: 1.3.0
* Python version: 3.10.10
* Operating System: MacOS Catalina version 10.15.7

### Description

Trying to run pharokka on a fasta file of ~2000 virus contigs, but getting an error in the tRNAscan-SE step (I believe).

### What I Did

```
Command I ran: pharokka.py -i /fastapath/fasta.fasta -o /outputdirpath -t 8 -f -g prodigal -m [with my file and folder paths]

Output: Running tRNAscan-SE. Applying meta mode.
Traceback (most recent call last):
  File "/pathtoenv/bin/pharokka.py", line 152, in <module>
    processes.concat_trnascan_meta(out_dir, num_fastas)
  File "/pathtoenv/bin/processes.py", line 195, in concat_trnascan_meta
    with open(fname) as infile:
FileNotFoundError: [Errno 2] No such file or directory: '/outputdirpath/input_split_tmp/trnascan_tmp1.gff'
```

### Additional info

It has created some files in the output directory, but does not seem to have finished. Log file ends at "Starting tRNA-scanSE. Applying meta mode."

**Comment by gbouras13** [comment]
Hi @phagecat,

Would you be able to have a look at hat is in the /outputdirpath/input_split_tmp directory and tell me what is in there? It seems like the temporary fff files are not in there when they should be.

George

**Comment by phagecat** [comment]
Hi @gbouras13, thanks for the reply! It looks like that directory contains individual fasta files for all of the input contigs (all called input_subprocess#.fasta)

**Comment by gbouras13** [comment]
Hi @phagecat, no worries.

Are there also phanotate files? There should be. 

Something is wrong with your trna-scanSE installation I think. I can't quite figure out but it's probably a more system wide issue, I am just guessing though at this stage.

So perhaps try running 

```
tRNAscan-SE --help
```

to see what you get. 

Also, I would try and take the first 5 contigs from your input, put them in a file (say call it subset.fasta) and try running pharokka on that. If that fails then it's definitely a global installation issue with pharokka. 

One other thing is that your Mac OS is pretty old - maybe updating that could help too if all else fails! Not sure.

George

**Comment by phagecat** [comment]
Hi again, I updated my OS and I still seem to be getting the same issue. I also tried running just 4 of the contigs with no luck. tRNAscan-SE --help seems to run ok, it showed the version (2.0.11), citation, usage, and options. I was running with prodigal and got a few files in the output directory: prodigal_aas_tmp.fasta, prodigal_out_tmp.fasta, and prodigal_out.gff. It also seems to have created a file called trnascan_out.gff with nothing in it.

**Comment by gbouras13** [comment]
That is a shame @phagecat - perhaps try running transcan on your input files to see what you get and hopefully it causes an error?

tRNAscan-SE input.fasta --thread 1 -G -Q -j out_test.gff

Otherwise perhaps try a fresh re-install of pharokka? I have a bad feeling trna scan is failing for some more abstract reason on your machine, so if we can’t figure it you perhaps it will be worth me opening an issue on the trnascan repo too.

George

**Comment by phagecat** [comment]
Just ran that and it did cause an error!
`Error: Parse failed (sequence file /var/folders/vl/plg9c28j1pvfjp2_4nt65tgh0000gn/T//tscan3178.trna):
Line 2: illegal character \`
It looks like it says the names of all of my contigs contain this symbol \ at the end of them, but I don't see that when I open the fasta file.

**Comment by gbouras13** [comment]
Well at least we found out why @phagecat ! 

I’m guessing it is a hidden character. I’d recommend using something like biopython to rename the contigs for all of them as it might break other programs too. 

Can I ask before I close this, what program did you generate the contigs from - in case others run into this issue!

George

**Comment by phagecat** [comment]
Great, will definitely try that. I downloaded these contigs from IMG/VR.

**Comment by gbouras13** [comment]
@phagecat I hope you managed to rename the headers - I am closing this issue now.

George

**Comment by phagecat** [comment]
Hi again, just wanted to follow up that I cleaned up the fasta file and was able to run tRNAscan-SE on its own successfully, but am getting the exact same issue above when running pharokka.

**Comment by gbouras13** [comment]
Hi @phagecat , would you mind sharing the input (maybe over email), or if it is too big maybe a subset (e.g. 100 contigs)?


George
