### ISSUE TITLE
specify in documentation that --terminase_start requires strand-specific coordinate

### ISSUE THREAD

**Issue by acvill** [gbouras13/pharokka#261]
* pharokka version: 1.3.2
* Python version: 3.9.16
* Operating System: Rocky Linux 9.0 (Blue Onyx)

Thanks for making and maintaining pharokka. It's a great tool.

After some troubleshooting, I realized that `--terminase_start` requires the `end` (right) coordinate from the gff when `--terminase_strand neg` is specified. My example:

### gff line describing terminase large subunit
```
ON631220.1    PHANOTATE    CDS    80073    82226    -1.721062366005452e+16    -    ...
```
### incorrect use of `--terminase`
```
pharokka.py \
  -i <fasta file> \
  -o <output folder> \
  -d <path/to/database_dir> \
  -t <threads> \
  --terminase \
  --terminase_start 80073 \
  --terminase_strand neg
```

### correct use of `--terminase`
```
pharokka.py \
  -i <fasta file> \
  -o <output folder> \
  -d <path/to/database_dir> \
  -t <threads> \
  --terminase \
  --terminase_start 82226 \
  --terminase_strand neg
```

It would be nice if you could mention explicitly in the documentation that `--terminase` expects the true strand-specific start position of the terminase large subunit and *not* the coordinate specified in the `start` field of the un-reoriented gff file.

**Comment by gbouras13** [comment]
Hi @acvill

Thanks for this! I will some more details to the documentation.

George
