### ISSUE TITLE
--label_hypotheticals

### ISSUE THREAD

**Issue by hmdaahmd** [gbouras13/pharokka#263]
* phrokka version: 1.3.2
* Python version: 3.9.16
* Operating System: 

### Description
I'm trying to plot a phage genome using this script: $ pharokka_plotter.py -i input.fasta -n pharokka_plot -o pharokka_output_directory --label_hypotheticals 

Is there a way to label only a specefic hypothetical protein based on its ID in gff/gbk file, 
"--label_hypotheticals" flag labels all  hypothetical proteins

```

```

**Comment by gbouras13** [comment]
Hi @hmdaahmd,

This is a good suggestion. You cannot do it right now.

 I will aim to implement something soon, it shouldn't be too hard.

Perhaps something like putting in a list of IDs with a flag like `--label_ids`.

George

**Comment by hmdaahmd** [comment]
Hi George,

It would be a great addition!

Thank you,
Hamed

**Comment by gbouras13** [comment]
Fixed by #275
