### ISSUE TITLE
Fixed GBK translation when non-11 coding tables used

### ISSUE THREAD

**Issue by alegione** [gbouras13/pharokka#268]
* phrokka version: 1.3.2
* Python version: 3.11 (I think)
* Operating System: ubuntu

### Description

Generating annotations for translation table 4 would initially output a correct temporary prodigal file, but the final gbk would contain incorrect translations

### What I Did
Hi there, 
I noted that you had non-standard coding tables in as experimental, I was keen to get it to work so forked your repro and I think worked through the code that was resulting in standard bacterial (11) table gbks being output even when a different coding table was selected.

This was mostly around the biopython code for 'translate' that was missing the 'table=' option, so even when a different coding table was selected and annotated with prodigal, the gbk translation from the fasta file would treat it as table 11 every time.

Happy to submit a pull request but thought I best put it here first.

**Comment by gbouras13** [comment]
@alegione thanks, I appreciate this a lot! I’m currently on holidays but will have a look at this in detail (and merge it in with a PR ) when I get back in a few weeks. Planning on adding tests and other goodies too so more of these bugs can be picked up. 

George

**Comment by alegione** [comment]
No problem, I'm in no rush, have used my forked repo for now - I have definitely not added in tests :D sorry! only tweaked a few lines

**Comment by gbouras13** [comment]
Fixed by #269
