### ISSUE TITLE
Plotter inclusive of AMR genes and VFs?

### ISSUE THREAD

**Issue by mhmism** [gbouras13/pharokka#270]
Thank you for this amazing tool!

Is it possible to annotate/color genes related to AMR or VFs within the pharokka plotter?

**Comment by gbouras13** [comment]
Hi @mhmism,

this is a great idea (you can’t right now) - will put it on to do list for the next update.

George

**Comment by mhmism** [comment]
Exciting! I will be looking forward to the next update! 

Thanks!

**Comment by gbouras13** [comment]
Fixed by #275
