### ISSUE TITLE
Cannot get pharokka databases installed

### ISSUE THREAD

**Issue by Jlee795** [gbouras13/pharokka#304]
* pharokka version: 1.5
* Python version: 3.7.3
* Operating System: linux cluster

### Description
Trying to install the latest version of pharokka 1.5 and conda installs weren't working. Tried using micromamba and that still hasn't worked. went through a git clone and someone sent a yml file, still can't get the databases installed (see commands and errors below).

### What I Did
pip install -e .

Obtaining file:///home/crk_w19039039/pharokka
Collecting setuptools>=67.7.2 (from Pharokka==1.5.1)
  Using cached https://files.pythonhosted.org/packages/c7/42/be1c7bbdd83e1bfb160c94b9cafd8e25efc7400346cf7ccdbdb452c467fa/setuptools-68.0.0-py3-none-any.whl
Collecting loguru>=0.5.4 (from Pharokka==1.5.1)
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/03/0a/4f6fed21aa246c6b49b561ca55facacc2a44b87d65b8b92362a8e99ba202/loguru-0.7.2-py3-none-any.whl
Collecting pyyaml>=6.0 (from Pharokka==1.5.1)
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/cd/e5/af35f7ea75cf72f2cd079c95ee16797de7cd71f29ea7c68ae5ce7be1eda0/PyYAML-6.0.1.tar.gz (125kB)
    100% |████████████████████████████████| 133kB 4.7MB/s
  Cache entry deserialization failed, entry ignored
  Installing build dependencies ... done
Collecting pandas>=1.4.2 (from Pharokka==1.5.1)
  Could not find a version that satisfies the requirement pandas>=1.4.2 (from Pharokka==1.5.1) (from versions: 0.1, 0.2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 0.19.2, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0, 0.21.1, 0.22.0, 0.23.0, 0.23.1, 0.23.2, 0.23.3, 0.23.4, 0.24.0, 0.24.1, 0.24.2, 0.25.0, 0.25.1, 0.25.2, 0.25.3, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5)
No matching distribution found for pandas>=1.4.2 (from Pharokka==1.5.1)

did this command:

install_databases.py -d
Traceback (most recent call last):
  File "/home/crk_w19039039/pharokka/bin/install_databases.py", line 7, in <module>
    from databases import instantiate_install
  File "/home/crk_w19039039/pharokka/bin/databases.py", line 30, in <module>
    from alive_progress import alive_bar
ModuleNotFoundError: No module named 'alive_progress'

so did this:
pip install alive-progress

Collecting alive-progress
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/d5/81/91e164705bdf4e2774cea59f566a41ab25f3c87affd716516fc8b03a4039/alive_progress-3.1.5-py3-none-any.whl
Collecting about-time==4.2.1 (from alive-progress)
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/fb/cd/7ee00d6aa023b1d0551da0da5fee3bc23c3eeea632fbfc5126d1fec52b7e/about_time-4.2.1-py3-none-any.whl
Collecting grapheme==0.6.0 (from alive-progress)
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/ce/e7/bbaab0d2a33e07c8278910c1d0d8d4f3781293dfbc70b5c38197159046bf/grapheme-0.6.0.tar.gz
Building wheels for collected packages: grapheme
  Running setup.py bdist_wheel for grapheme ... done
  Stored in directory: /home/crk_w19039039/.cache/pip/wheels/1e/f7/2c/341b06952dda321b8550d9ebd573dff4c0640fa710d9f23ecd
Successfully built grapheme
twisted 18.7.0 requires PyHamcrest>=1.9.0, which is not installed.
conda 4.12.0 requires ruamel_yaml_conda>=0.11.14, which is not installed.
Installing collected packages: about-time, grapheme, alive-progress
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/cm/shared/crick-apps/anaconda3/5.3.1/lib/python3.7/site-packages/about_time'
Consider using the `--user` option or check the permissions.

went back to trying to install databases:

install_databases.py -d

Traceback (most recent call last):
  File "/home/crk_w19039039/pharokka/bin/install_databases.py", line 7, in <module>
    from databases import instantiate_install
  File "/home/crk_w19039039/pharokka/bin/databases.py", line 30, in <module>
    from alive_progress import alive_bar
ModuleNotFoundError: No module named 'alive_progress'

don't know what to do with this

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by gbouras13** [comment]
Hi @Jlee795 ,

This looks like a system issue for you. I'm not sure I can really help too much, it doesn't seem to be a problem with pharokka.

If you can't install things with pip e.g. `pip install alive-progress` fails, then there is a much deeper issue than conda or pharokka.

Based on the error messages

```
Permission denied: '/cm/shared/crick-apps/anaconda3/5.3.1/lib/python3.7/site-packages/about_time'
Consider using the --user option or check the permissions.
```

You might be lacking some permissions on your cluster. I'd contact the systems administrator for some advice.

George

**Comment by gbouras13** [comment]
maybe try  to uninstall then reinstall.

```
conda uninstall pyhmmer 

conda install pyhmmer 

# or

pip install pyhmmer
```

**Comment by Jlee795** [comment]
Hmm, thank you. I have just tried that and it is still displaying the same traceback error message relating to pyhmmer. I am not sure what is doing

**Comment by gbouras13** [comment]
I think it's just one of those cases where the cluster is having some difficulties :(

If you have a laptop or desktop handy I'd give that a go (assuming you don't have thousands of contains), Pharokka should handle it fine and probably easier to install!

**Comment by gbouras13** [comment]
Another option is this if you are struggling to install it https://usegalaxy.eu/?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fiuc%2Fpharokka%2Fpharokka%2F1.2.1%2Bgalaxy1&version=1.2.1%20galaxy1

It runs v1.3.2 but if you have lots of contigs, it might be a good option (in meta mode it won't be much different to v1.5.1)

**Comment by gbouras13** [comment]
Closing due to time since last post
