### ISSUE TITLE
what gene should we use to put at +1 in a Stx-phage assembly

### ISSUE THREAD

**Issue by splaisan** [gbouras13/pharokka#306]
Hi George, All,

disclaimer: sorry but I am not a bacteriologist nor a virolog ;-)

I do not find 'terminase' genes in my circularStx- phage assemblies although they are described in [Pinto et al 2021](https://doi.org/10.1186/s12864-021-07685-0) for this usage! 
Is this normal in a non-integrated form or is it due to flye 

I usually use `circlator fixstart` to put DnaA at +1 in bacterial assemblies and would like to also show nice maps for my phages.

Do you have a recommendation for the choice of the first gene to show on a bacteriophage map? Is the first shiga gene a good option?

thanks for your feedback and knowledge

**Comment by gbouras13** [comment]
Hi @splaisan,

I’ll come back with a more length explanation tomorrow (it’s late in Australia), but I have just the tool for you I think :)

https://github.com/gbouras13/dnaapler

**Comment by gbouras13** [comment]
Thanks @splaisan for you very kind words - I am trying to get Dnaapler published at JOSS, hopefully won't be too long :)

Another thing is that you can actually run Dnaapler within pharokka if you use `--dnaapler` - the reoriented phage is in the output directory.

If you do bacterial assemblies too, you may be interested in my tool Hybracter (https://github.com/gbouras13/hybracter) - a preprint for this one is coming very soon, and I'd love feedback if you try it out.

George

**Comment by splaisan** [comment]
Thanks George,

I indeed saw the option after receiving your message. I will include it next time. I did not know yet what dnaapler was then.

I can easily try Hybracter as I just performed bacterial assemblies which I rotated with circlator. I will redo this step and let you know.

cheers
