### ISSUE TITLE
phannote issues?

### ISSUE THREAD

**Issue by raw937** [gbouras13/pharokka#307]
* pharokka version: 1.5 and phanotate 1.5.1
* Python version: 3
* Operating System: linux

### Description

When comparing the current  phanotate 1.6.1 and 1.5.1 (within Pharokka) from lambda phage we get vastly different results from the called ORFs between the two versions. 

### What I Did

I have mentioned this to phanotate as well. The ORFs contain #, +, * from the resulting phanotate file from 1.6.1. But, I was unable to see if you filter out # symbols or whether you convert from fasta. I am curious how pharokka deals with this phanotate issue. As 1.5.1 doesn't seem to output a .faa (protein fasta file). 

Any thoughts? Are you converting the nucleotide fasta post phanotate ?

**Comment by gbouras13** [comment]
Hi @raw937 ,

I see your issue in Phanotate - almost certainly that is a very strange bug with the +, *,  #s!

I am not familiar with Phanotate v1.6. I want to make sure I can install Phanotate in pharokka via conda, so I use v1.5.1 as the latest stable version.

I've never (nor have any pharokka users to my knowledge) come across that bug so I would assume it was introduced in v1.6.

With pharokka, I translate the nucleotide output from phanotate to amino acid with biopython, as you can't get amino acid output directly from phanotate v1.5. If you run pharokka you can look at both as phanotate.faa and phanotate.fna in the output.

George

**Comment by gbouras13** [comment]
Closing as this question is not an outstanding bug with pharokka
