### ISSUE TITLE
Bioconda version is out of date

### ISSUE THREAD

**Issue by marade** [gbouras13/pharokka#310]
1.3.2  on Bioconda as of 2023-12-14

1.5.1 on Github as of 2023-10-25

**Comment by gbouras13** [comment]
Hi @marade,

The latest bioconda release is v1.5.1 - I try my best to sync PyPI, Conda and GitHub when I release an updated version.

https://anaconda.org/bioconda/pharokka

If you want to force install v1.5.1, please use something like:

```
mamba install pharokka==1.5.1
```

George

**Comment by marade** [comment]
Yes, looks like I had another package that was causing a downgrade through dependency issues. Thanks!
