### ISSUE TITLE
tRNAs are not being included in tbl file.

### ISSUE THREAD

**Issue by hmontenegro** [gbouras13/pharokka#323]
* pharokka version: 1.6.0
* Python version: 3.10.8
* Operating System: Rocky Linux 8

### Description

Conda-installed Pharokka 1.6.0. Annotation runs without issues, but tRNAs are not included in the tbl file. With Pahrokka 1.4.1, tRNAs are included in tbl file.

### What I Did

```
pharokka.py -t 16 -i assembly.fas -o annotation ~/DBs/Pharokka/1.4.0/
```

**Comment by gbouras13** [comment]
Hi @hmontenegro ,

v1.6.0 introduced a bug with the table creation - thanks for picking this up for me. I will shortly be releasing v1.6.1 with a fix.

George
