### ISSUE TITLE
question about pharokka_plotter.py and multi-contig .fasta

### ISSUE THREAD

**Issue by nsvarona** [gbouras13/pharokka#326]
* pharokka version: Pharokka v 1.3.0

The pharokka_plotter.py is a very cool new feature. Since it works for only a single contig, is there a workaround to run this with a multi-contig fasta? Or would you recommend catenating contigs to a single-line fasta before running pharokka? Thank you!

**Comment by aryehjc** [comment]
I would also like to ask the same question thanks

**Comment by gbouras13** [comment]
`pharokka_multiplotter.py` should achieve what you want - it will be available in v1.7.0

**Comment by aryehjc** [comment]
Thank you very much
