### ISSUE TITLE
Wrong attribute - PyHMMER module 

### ISSUE THREAD

**Issue by valentynbez** [gbouras13/pharokka#328]
* pharokka version: 1.2.1
* Python version: 3.10.10
* Operating System: CentOS8
* PyHMMER version: 0.10.4

During PyHMMER run [code](https://github.com/gbouras13/pharokka/blob/b1173c8bdc38a85ff8769fb15c8f2fb223bd6b9b/bin/hmm.py#L57-L59) refers to `hit.phrog` attribute. `pyhmmer.plan7.Hit` object doesnt have attribute `phrog`, therefore code crashes. 
To get the phrog name and compare it `hit.name.decode()` should be used. 
This was a tricky one as it only happened during a very big annotation job.

**Comment by gbouras13** [comment]
Thanks for spotting the bug @valentynbez and for the PR - just checking, this would be for v1.6.1?

**Comment by valentynbez** [comment]
Yes, code in these sections remained unchanged since 1.2.1. 
I just didn't update my environment for a long time.
