### ISSUE TITLE
Inquiry on Pharokka

### ISSUE THREAD

**Issue by songmj86** [gbouras13/pharokka#342]
* pharokka version: 1.7.1
* Python version: 3.10.8
* Operating System: Ubuntu 22.04.4 LTS

### Inquiry

Hi 

I would like to ask any plan or possibility that Pharokka will attemps to use prodigal-gv for virus-specific gene calling and 
KEGG numbers to annotate genes as class I and II AMG (https://www.sciencedirect.com/science/article/pii/S1369527416300376)

Thanks for developing such a nice tool ! 

Best regards

**Comment by songmj86** [comment]
Hi ! 

I apologize first that pharokka uses prodigal-gv for gene calling.

What I want to ask you was indeed that "is there any plan to use CDS as inputs as some of my genes need to be structually called as either single or meta mode for prodigal-gv (Pharokka does not seem to distinguish the parameters)" ?? 

Thanks !

**Comment by gbouras13** [comment]
Hi @songmj86 ,

prodigal-gv must be run in meta-mode always (to incorporate the alternative genetic code models) - there is no way to specify single mode.

And thank you for that link - Pharokka doesn't support Class I/II AMGs (yet) but I will have a read and consider adding it!

George

**Comment by songmj86** [comment]
Oh! Thanks for quick response!
