### ISSUE TITLE
Google Colab error

### ISSUE THREAD

**Issue by CristianUNR** [gbouras13/pharokka#349]
* pharokka version: 1.7.1
* Python version: 3.1
* Operating System: Google Colab 

### Description

I am trying to run pharokka in google colab, but when I get to point 3 I get this error: 
Error occurred: Command 'pharokka.py -d pharokka_db -i phage.fasta -t 4 -o output_pharokka -p pharokka -l Default -g phanotate -f --fast' returned non-zero exit status 1.
The fasta file for the genome was correctly upload. 
Thanks in advance

**Comment by seanrjohnson** [comment]
I am seeing the same error.

Changing the subprocess.run line to:
```
result = subprocess.run(command, shell=True, check=True, stderr=subprocess.PIPE, stdout=subprocess.PIPE)
```
and the catch to:
```
except subprocess.CalledProcessError as e:
    print(f"Error occurred: {e}")
    print(f"stderr: {e.stderr.decode('utf-8')}")
    print(f"stdout: {e.stdout.decode('utf-8')}")
```
Gives some extra info about what the error is. But it's kind of inscrutable to me. Something about database validation. I closed my colab window already, so I don't have the exact error.

**Comment by gbouras13** [comment]
Hi @seanrjohnson @CristianUNR ,

Thanks for spotting this - the issue was with the Mambaforge installation (the URL is dead) - so Pharokka was not being installed whatsoever. 

I'll fix this today.

George

**Comment by gbouras13** [comment]
Should be working now at this link - closing the issue, but if the error persists let me know and reopen it.

https://colab.research.google.com/github/gbouras13/pharokka/blob/master/run_pharokka_and_phold_and_phynteny.ipynb

George
