### ISSUE TITLE
Pharokka slow (Phanotate step)

### ISSUE THREAD

**Issue by mdtorohernando** [gbouras13/pharokka#365]
* pharokka version: 1.7.2
* Python version: 3.10.14
* Operating System: Ubuntu 20.04.3.LTS / Intel® Core™ i9-10980XE CPU @ 3.00GHz × 36 / 256 Gb RAM / NVIDIA Corporation GP108 [GeForce GT 1030]

### Description

Hello! I am trying to use Pharokka for the annotation of phage genomes in some E. coli single genomes sequenced with Nanopore. These genomes are in about 2-5 contigs, with the chromosome in a single contig. According to the program's documentation, this process shouldn't take too long; however, in my case, the genome has been stuck in Phanotate for almost an hour. I'm not sure if this is normal. 

I've tried both the normal mode and the fast mode in Pharokka. Besides, I'm trying to use my 36 nodes. 

### What I Did

```
pharokka.py -i genome.fasta -o genome.pharokka -d /home/pgen/miniconda3/envs/Pharokka/databases/pharokka_v1.4.0_databases -t 36 -p genome

pharokka.py -i genome.fasta -o genome.pharokka_fast -d /home/pgen/miniconda3/envs/Pharokka/databases/pharokka_v1.4.0_databases -t 36 --fast -p genome
```

**Comment by gbouras13** [comment]
Hi @mdtorohernando ,

The issue is phanotate - try with `-g prodigal`. I don't the details, but the phanotate algorithm is not linear complexity, so tends to fail for contigs > 1MB (to be fair it was designed with phages in mind!)

George

**Comment by mdtorohernando** [comment]
Thank you very much!!! Yuhuuuu!!!! 4 minutes per genome!!
Thanks!
