### ISSUE TITLE
If your pharokka `v1.7.3` installation isn't working as dnaapler isn't installed, try `pip install dnaapler==0.8.1`. This will be fixed soon

### ISSUE THREAD

**Issue by gbouras13** [gbouras13/pharokka#370]

**Comment by gbouras13** [comment]
fixed in `v1.7.4`

**Comment by cyfr** [comment]
I still had to downgrade to this to make pharokka work, on a macbook system. Tried dnaapler 1.0.0, 1.0.1 and most recent version, and pharokka refused to run because it was the "wrong version".
